/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author acer
 */
public class playjagung extends javax.swing.JFrame {

    public playjagung() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        map = new javax.swing.JToggleButton();
        airbutton = new javax.swing.JLabel();
        pupukbutton = new javax.swing.JLabel();
        obat1button = new javax.swing.JLabel();
        obat2button = new javax.swing.JLabel();
        guntingbutton = new javax.swing.JLabel();
        panenbutton = new javax.swing.JLabel();
        boxtanaman = new javax.swing.JLabel();
        boxgerak = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        map.setText("map");
        map.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 81, -1));

        airbutton.setBackground(new java.awt.Color(255, 255, 255));
        airbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/water can.png"))); // NOI18N
        airbutton.setText("air");
        airbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(airbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 80, 80));

        pupukbutton.setText("pupuk");
        pupukbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(pupukbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 80, 80));

        obat1button.setText("obat 1");
        obat1button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(obat1button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 183, 80, 80));

        obat2button.setText("obat 2");
        obat2button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(obat2button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 272, 80, 80));

        guntingbutton.setText("gunting");
        guntingbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(guntingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 363, 80, 80));

        panenbutton.setText("panen");
        panenbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(panenbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 449, 80, 80));

        boxtanaman.setText("tanaman");
        getContentPane().add(boxtanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 300, 400));

        boxgerak.setText("boxgerak");
        getContentPane().add(boxgerak, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 250, 200));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 110, 560));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background jagung.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public void map(ActionListener action) {
        map.addActionListener(action);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playjagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playjagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playjagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playjagung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playjagung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airbutton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel boxgerak;
    private javax.swing.JLabel boxtanaman;
    private javax.swing.JLabel guntingbutton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton map;
    private javax.swing.JLabel obat1button;
    private javax.swing.JLabel obat2button;
    private javax.swing.JLabel panenbutton;
    private javax.swing.JLabel pupukbutton;
    // End of variables declaration//GEN-END:variables
}
