/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author acer
 */
public class playtebu extends javax.swing.JFrame {

    public playtebu() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        map = new javax.swing.JToggleButton();
        tmbsiram = new javax.swing.JButton();
        boxtanaman = new javax.swing.JLabel();
        boxgerak = new javax.swing.JLabel();
        boxhp = new javax.swing.JLabel();
        tmbobat1 = new javax.swing.JButton();
        tmbobat2 = new javax.swing.JButton();
        tmbpupuk = new javax.swing.JButton();
        tmbgunting = new javax.swing.JButton();
        tmbpanen = new javax.swing.JButton();
        boxumur = new javax.swing.JLabel();
        btnstop = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        map.setText("map");
        getContentPane().add(map, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 68, -1));

        tmbsiram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/water can.png"))); // NOI18N
        tmbsiram.setText("jButton1");
        tmbsiram.setBorderPainted(false);
        tmbsiram.setContentAreaFilled(false);
        getContentPane().add(tmbsiram, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 80));

        boxtanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tebu1.gif"))); // NOI18N
        getContentPane().add(boxtanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 300, 400));

        boxgerak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/emptybox.png"))); // NOI18N
        boxgerak.setText("boxgerak");
        getContentPane().add(boxgerak, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 250, 200));

        boxhp.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        boxhp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/health4.png"))); // NOI18N
        boxhp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(boxhp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 120, 40));

        tmbobat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat1.png"))); // NOI18N
        tmbobat1.setText("jButton1");
        tmbobat1.setBorderPainted(false);
        tmbobat1.setContentAreaFilled(false);
        getContentPane().add(tmbobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 80));

        tmbobat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat2.png"))); // NOI18N
        tmbobat2.setText("jButton2");
        tmbobat2.setBorderPainted(false);
        tmbobat2.setContentAreaFilled(false);
        getContentPane().add(tmbobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 80));

        tmbpupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pupuk1.png"))); // NOI18N
        tmbpupuk.setText("jButton3");
        tmbpupuk.setBorderPainted(false);
        tmbpupuk.setContentAreaFilled(false);
        getContentPane().add(tmbpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 80, 80));

        tmbgunting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tangan.png"))); // NOI18N
        tmbgunting.setText("jButton4");
        tmbgunting.setBorderPainted(false);
        tmbgunting.setContentAreaFilled(false);
        getContentPane().add(tmbgunting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 80));

        tmbpanen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cluritPKI.png"))); // NOI18N
        tmbpanen.setText("jButton5");
        tmbpanen.setBorderPainted(false);
        tmbpanen.setContentAreaFilled(false);
        getContentPane().add(tmbpanen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, 80));

        boxumur.setFont(new java.awt.Font("Humnst777 Blk BT", 0, 18)); // NOI18N
        getContentPane().add(boxumur, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 10, 80, 40));

        btnstop.setText("stop");
        getContentPane().add(btnstop, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background jagung.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background jagung.png"))); // NOI18N
        jLabel.setText("jLabel1");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void map(ActionListener action) {
        map.addActionListener(action);
    }
    
    public void kliksiram(ActionListener action) {
        tmbsiram.addActionListener(action);
    }
    
    public void klikobat1(ActionListener action) {
        tmbobat1.addActionListener(action);
    }
    
    public void klikobat2(ActionListener action) {
        tmbobat2.addActionListener(action);
    }
    
    public void klikspupuk(ActionListener action) {
        tmbpupuk.addActionListener(action);
    }
    
    public void klikgunting(ActionListener action) {
        tmbsiram.addActionListener(action);
    }
    
    public void klikpanen(ActionListener action) {
        tmbpanen.addActionListener(action);
    }
    
    public void settanaman(String tanaman) {
        boxtanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource(tanaman)));
    }
    
    public void setboxgerak(String nama) {
        boxgerak.setIcon(new javax.swing.ImageIcon(getClass().getResource(nama)));
    }
    public void stop(ActionListener action) {
        btnstop.addActionListener(action);
    }

    public void setvisibleboxgerak(boolean bool) {
        boxgerak.setVisible(bool);
    }

    public void setboxumur(String nama) {
        boxumur.setText(nama);
    }

    public void setboxhp(String nama) {
        boxhp.setText(nama);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playtebu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playtebu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playtebu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playtebu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playtebu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel boxgerak;
    private javax.swing.JLabel boxhp;
    private javax.swing.JLabel boxtanaman;
    private javax.swing.JLabel boxumur;
    private javax.swing.JButton btnstop;
    private javax.swing.JLabel jLabel;
    private javax.swing.JToggleButton map;
    private javax.swing.JButton tmbgunting;
    private javax.swing.JButton tmbobat1;
    private javax.swing.JButton tmbobat2;
    private javax.swing.JButton tmbpanen;
    private javax.swing.JButton tmbpupuk;
    private javax.swing.JButton tmbsiram;
    // End of variables declaration//GEN-END:variables
}
