/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author acer
 */
public class scorepemain extends javax.swing.JFrame {

    /**
     * Creates new form scorepemain
     */
    public scorepemain() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public void setnama(String namanya) {
        nama.setText(namanya);
    }

    public void setscore(String scorenya) {
        score.setText(scorenya);
    }

    public void klikback(ActionListener action) {
        back.addActionListener(action);
    }

    public void klikhighscore(ActionListener action) {
        highscore.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        score = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        highscore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        score.setText("ef");
        score.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 190, 80));

        nama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nama.setText("nama");
        nama.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 190, 80));

        back.setText("back");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 90, 50));

        highscore.setText("highscore");
        getContentPane().add(highscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 120, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/papanSkor.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 720, 470));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/score.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scorepemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scorepemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scorepemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scorepemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scorepemain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton highscore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
