/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class toko extends javax.swing.JFrame {

    /**
     * Creates new form toko
     */
    public toko() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        beliobat1 = new javax.swing.JButton();
        beliobat2 = new javax.swing.JButton();
        belipupuk = new javax.swing.JButton();
        beliair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setuang = new javax.swing.JLabel();
        setobat1 = new javax.swing.JLabel();
        setobat2 = new javax.swing.JLabel();
        setpupuk = new javax.swing.JLabel();
        setair = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pupuk1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/water can.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 100, -1));

        beliobat1.setText("beli");
        getContentPane().add(beliobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        beliobat2.setText("beli");
        getContentPane().add(beliobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        belipupuk.setText("beli");
        getContentPane().add(belipupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        beliair.setText("beli");
        getContentPane().add(beliair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel1.setText("2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel6.setText("2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jLabel7.setText("2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jLabel8.setText("1");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));
        getContentPane().add(setuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 10, 50, 20));
        getContentPane().add(setobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 50, 20));
        getContentPane().add(setobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 40, 30));
        getContentPane().add(setpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, 20));
        getContentPane().add(setair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 234, 50, 20));

        kembali.setText("kembali");
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/shop.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void setuang(String data) {
        setuang.setText(data);
    }
    public void setpupuk(String data) {
        setpupuk.setText(data);
    }

    public void setobat1(String data) {
        setobat1.setText(data);
    }

    public void setobat2(String data) {
        setobat2.setText(data);
    }

    public void setair(String data) {
        setair.setText(data);
    }

    public void klikbeliair(ActionListener action) {
        beliair.addActionListener(action);
    }

    public void klikbelipupuk(ActionListener action) {
        belipupuk.addActionListener(action);
    }
    public void klikkembali(ActionListener action) {
        kembali.addActionListener(action);
    }

    public void klikbeliobat1(ActionListener action) {
        beliobat1.addActionListener(action);
    }

    public void klikbeliobat2(ActionListener action) {
        beliobat2.addActionListener(action);
    }
 public void message(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton beliair;
    private javax.swing.JButton beliobat1;
    private javax.swing.JButton beliobat2;
    private javax.swing.JButton belipupuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel setair;
    private javax.swing.JLabel setobat1;
    private javax.swing.JLabel setobat2;
    private javax.swing.JLabel setpupuk;
    private javax.swing.JLabel setuang;
    // End of variables declaration//GEN-END:variables

}
