/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class toko extends javax.swing.JFrame {

    /**
     * Creates new form toko
     */
    public toko() {
        initComponents();
        jual.setVisible(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        beliobat1 = new javax.swing.JButton();
        beliobat2 = new javax.swing.JButton();
        belipupuk = new javax.swing.JButton();
        beliair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setuang = new javax.swing.JLabel();
        setobat1 = new javax.swing.JLabel();
        setobat2 = new javax.swing.JLabel();
        setpupuk = new javax.swing.JLabel();
        setair = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        icongambar = new javax.swing.JLabel();
        jual = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/obat2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pupuk1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/water can.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 80));

        beliobat1.setText("beli");
        getContentPane().add(beliobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        beliobat2.setText("beli");
        getContentPane().add(beliobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        belipupuk.setText("beli");
        getContentPane().add(belipupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, 30));

        beliair.setText("beli");
        getContentPane().add(beliair, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        jLabel1.setText("2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 70, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        jLabel6.setText("2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 60, -1));

        jLabel7.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        jLabel7.setText("10");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 70, 70));

        jLabel8.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        jLabel8.setText("5");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 60, -1));

        setuang.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        setuang.setForeground(new java.awt.Color(0, 102, 153));
        setuang.setText("0");
        getContentPane().add(setuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 10, 70, 50));

        setobat1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        setobat1.setForeground(new java.awt.Color(0, 255, 255));
        setobat1.setText("0");
        getContentPane().add(setobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 30, 40));

        setobat2.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        setobat2.setForeground(new java.awt.Color(255, 255, 0));
        setobat2.setText("0");
        getContentPane().add(setobat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 30, 30));

        setpupuk.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        setpupuk.setForeground(new java.awt.Color(153, 153, 153));
        setpupuk.setText("0");
        getContentPane().add(setpupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 30, 40));

        setair.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        setair.setForeground(new java.awt.Color(0, 255, 204));
        setair.setText("0");
        getContentPane().add(setair, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 30, 30));

        kembali.setText("kembali");
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 490, 300));
        getContentPane().add(icongambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 120, 120));

        jual.setText("jual");
        getContentPane().add(jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/shop.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void setuang(String data) {
        setuang.setText(data);
    }
    public void setpupuk(String data) {
        setpupuk.setText(data);
    }

    public void setobat1(String data) {
        setobat1.setText(data);
    }

    public void setobat2(String data) {
        setobat2.setText(data);
    }

    public void setair(String data) {
        setair.setText(data);
    }

    public void klikbeliair(ActionListener action) {
        beliair.addActionListener(action);
    }

    public void klikbelipupuk(ActionListener action) {
        belipupuk.addActionListener(action);
    }
    public void klikkembali(ActionListener action) {
        kembali.addActionListener(action);
    }

    public void klikbeliobat1(ActionListener action) {
        beliobat1.addActionListener(action);
    }

    public void klikbeliobat2(ActionListener action) {
        beliobat2.addActionListener(action);
    }
    public void klikjualbarang(ActionListener action) {
        jual.addActionListener(action);
    }
    public void setgambar (String set){
        if (set.equalsIgnoreCase("jagung")) {
            icongambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jualjagung.png")));
            jual.setVisible(true);
        }
        if (set.equalsIgnoreCase("tebu")) {
            icongambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jualtebu.png")));
            jual.setVisible(true);
        }
        if (set.equalsIgnoreCase("tembakau")) {
            icongambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jualtembakau.png")));
            jual.setVisible(true);
        }
        if (set.equalsIgnoreCase("")) {
            icongambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            jual.setVisible(false);
        }
    }
 public void message(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton beliair;
    private javax.swing.JButton beliobat1;
    private javax.swing.JButton beliobat2;
    private javax.swing.JButton belipupuk;
    private javax.swing.JLabel icongambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jual;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel setair;
    private javax.swing.JLabel setobat1;
    private javax.swing.JLabel setobat2;
    private javax.swing.JLabel setpupuk;
    private javax.swing.JLabel setuang;
    // End of variables declaration//GEN-END:variables

}
